apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  {{- if eq .Values.env "prod" }}
  {{- toYaml .Values.autoscalingParams.prod | nindent 2 }}
  {{- else if eq .Values.env "staging" }}
  {{- toYaml .Values.autoscalingParams.staging | nindent 2 }}
  {{- else }}
  {{- toYaml .Values.autoscalingParams.dev | nindent 2 }}
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscalingParams.cpuTh }}
